Repository umc-5th-hackathon-team-I/Server, pull requests merged in 2024-01, with the labels that each got.

#2 [CHORE] Swagger setting
  .gitignore
  build.gradle
  src/main/java/com/teami/domain/test/controller/SwaggerTestController.java
  src/main/java/com/teami/domain/test/dto/TestRequest.java
  src/main/java/com/teami/domain/test/dto/TestResponse.java
  src/main/java/com/teami/domain/test/mapper/TestMapper.java
  src/main/java/com/teami/domain/test/service/SwaggerTestService.java
  src/main/resources/application.properties
Labels: chore

#4 [FEAT] create Mission api 구현
  src/main/java/com/teami/domain/mission/controller/MissionController.java
  src/main/java/com/teami/domain/mission/dto/request/ChatGPTRequest.java
  src/main/java/com/teami/domain/mission/dto/request/ChatRequest.java
  src/main/java/com/teami/domain/mission/service/MissionService.java
  src/main/java/com/teami/domain/test/controller/SwaggerTestController.java
Labels: feat

#6 [CHORE] Create Entity
  src/main/java/com/teami/domain/calendar/entitty/Calendar.java
  src/main/java/com/teami/domain/calendar/entitty/CalendarVisitor.java
  src/main/java/com/teami/domain/member/entitty/Friend.java
  src/main/java/com/teami/domain/member/entitty/Member.java
  src/main/java/com/teami/domain/mission/entity/CalendarMission.java
  src/main/java/com/teami/domain/mission/entity/Mission.java
  src/main/java/com/teami/domain/reward/entity/MemberReward.java
  src/main/java/com/teami/domain/reward/entity/Reward.java
  src/main/java/com/teami/global/common/BaseEntity.java
Labels: chore, feat

#17 [FEAT] 캘린더 및 미션 관련 API 구현
  src/main/java/com/teami/domain/calendar/controller/CalendarController.java
  src/main/java/com/teami/domain/calendar/dto/response/CalendarMissionIdResponse.java
  src/main/java/com/teami/domain/calendar/dto/response/CalendarMissionResponse.java
  src/main/java/com/teami/domain/calendar/dto/response/CalendarMissionsResponse.java
  src/main/java/com/teami/domain/calendar/entitty/Calendar.java
  src/main/java/com/teami/domain/calendar/entitty/CalendarMission.java
  src/main/java/com/teami/domain/calendar/mapper/CalendarMapper.java
  src/main/java/com/teami/domain/calendar/repository/CalendarMissionRepository.java
  src/main/java/com/teami/domain/calendar/repository/CalendarRepository.java
  src/main/java/com/teami/domain/calendar/service/CalendarService.java
  src/main/java/com/teami/domain/member/repository/MemberRepository.java
  src/main/java/com/teami/domain/member/service/MemberService.java
  src/main/java/com/teami/domain/mission/controller/MissionController.java
  src/main/java/com/teami/domain/mission/dto/response/NewMissionResponse.java
  src/main/java/com/teami/domain/mission/service/MissionService.java
  src/main/java/com/teami/global/apiPayload/ApiResponse.java
  src/main/java/com/teami/global/apiPayload/code/status/CommonErrorStatus.java
  src/main/java/com/teami/global/apiPayload/code/status/ErrorStatus.java
Labels: feat

#20 [Feat] 친구 추가, 목록, 캘린더 조회, 삭제 API를 구현한다
  .gitignore
  build.gradle
  src/main/java/com/teami/domain/calendar/controller/dto/response/CalendarInfo.java
  src/main/java/com/teami/domain/friend/controller/FriendController.java
  src/main/java/com/teami/domain/friend/controller/dto/response/FriendCalendarInfo.java
  src/main/java/com/teami/domain/friend/controller/dto/response/FriendInfo.java
  src/main/java/com/teami/domain/friend/controller/dto/response/FriendListResponse.java
  src/main/java/com/teami/domain/friend/entity/Friend.java
  src/main/java/com/teami/domain/friend/entity/FriendRepository.java
  src/main/java/com/teami/domain/friend/service/FriendService.java
  src/main/java/com/teami/domain/member/entitty/Friend.java
  src/main/java/com/teami/domain/member/entitty/Member.java
  src/main/java/com/teami/domain/member/entitty/MemberRepository.java
  src/main/java/com/teami/domain/member/service/MemberService.java
  src/main/java/com/teami/domain/test/controller/SwaggerTestController.java
  src/main/java/com/teami/global/apiPayload/ApiResponse.java
  src/main/java/com/teami/global/apiPayload/ExceptionHandler.java
  src/main/java/com/teami/global/apiPayload/code/BaseCode.java
  src/main/java/com/teami/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/teami/global/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/teami/global/apiPayload/code/ReasonDTO.java
  src/main/java/com/teami/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/teami/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/teami/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/teami/global/apiPayload/exception/GeneralException.java
  src/main/java/com/teami/global/common/BaseEntity.java
Labels: feat
